CREATE DATABASE IF NOT EXISTS fc25
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE fc25;

CREATE TABLE IF NOT EXISTS CoinTotal (
    id INT AUTO_INCREMENT PRIMARY KEY,    
    total INT NOT NULL,        
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE IF NOT EXISTS ItemSales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,        
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ItemSeenPrice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,        
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Bids (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bid INT NOT NULL,
    resale_estimate INT NOT NULL,
    outcome VARCHAR(16) NOT NULL DEFAULT 'open',
    sold_price INT NULL,
    minimum_bid INT NULL,
    current_bid INT NULL,
    buy_now INT NULL,
    minutes_left INT NULL,
    ask_count INT NULL,
    listed_price INT NULL,
    segment VARCHAR(32) NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL
);


CREATE TABLE IF NOT EXISTS CompareReads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    asks TEXT NOT NULL,
    page_count INT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
