CREATE DATABASE IF NOT EXISTS fc25
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE fc25;

CREATE TABLE IF NOT EXISTS CoinTotal (
    id INT AUTO_INCREMENT PRIMARY KEY,    
    total INT NOT NULL,        
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE IF NOT EXISTS ItemSales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,        
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ItemSeenPrice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,        
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Bids (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bid INT NOT NULL,
    resale_estimate INT NOT NULL,
    outcome VARCHAR(16) NOT NULL DEFAULT 'open',
    sold_price INT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL
);
