namespace Automation.Trading;

public static class BiddingStrategy
{
    public const uint MARGIN_COINS = 700;
    public const uint MIN_AUCTION_MINUTES = 0;
    public const uint MAX_AUCTION_MINUTES = 20;
    public const double MAX_EXPOSURE_SHARE = 0.5;
    public const uint RESALE_WINDOW_DAYS = 7;
    public const int RESALE_SAMPLE_SIZE = 3;
    public const uint RESALE_MAX_AGE_HOURS = 6;
    public const uint OPEN_BID_TIMEOUT_HOURS = 2;
    public const int MIN_COMPARE_LISTINGS = 2;
    public const int MAX_COMPARE_PAGES = 2;
    public const int MAX_COMPARE_PAGES_FOR_LISTING = 1;
    public const uint LOOP_MINUTES_DEFAULT = 10;
    public const int MAX_RESULT_PAGES = 100;
    public const int SCAN_BUDGET_SECONDS = 120;
    public const uint MAX_TRANSFER_LIST = 100;
    public const uint CLUB_ITEM_MAX_BID = 500;
    public const uint CLUB_ITEM_MIN_BUY_NOW = 1000;
    public const uint PLAYER_MAX_BID = 500;
    public const uint PLAYER_MIN_BUY_NOW = 1000;
    public const string PLAYER_QUALITY = "Silver";
    public const uint CALIBRATION_WINDOW_DAYS = 14;
    public const int CALIBRATION_PRIOR_WEIGHT = 5;
    public const double CALIBRATION_MIN_RATIO = 0.5;
    public const double CALIBRATION_MAX_RATIO = 1.2;
    public const int ITEM_SALES_MIN = 2;
    public const double SALES_MAX_UPLIFT = 1.5;
    public const uint SEGMENT_WINDOW_DAYS = 7;
    public const int SEGMENT_MIN_RESOLVED_BIDS = 10;
    public const double SEGMENT_MIN_WIN_RATE = 0.10;
    public const uint SEGMENT_COOLDOWN_HOURS = 6;
    public const uint SEGMENT_PROBE_BIDS = 3;
    public const int SNIPE_BATCH_SIZE = 15;
    public const uint SNIPE_MAX_BID = 1500;
    public const int SNIPE_POLL_MS = 1000;
    public const uint SNIPE_MAX_MINUTES = 25;
    public const int SNIPE_AIM_SECONDS = 15;
    public const bool NETWORK_OBSERVER = true;
    public const int PAGE_TURN_GAP_MS = 2500;
    public const int PAGE_TURN_JITTER_MIN_MS = 500;
    public const int PAGE_TURN_JITTER_MAX_MS = 1000;
    public const int COMPARE_READ_GAP_MS = 3000;
    public const int SEARCHES_PER_MINUTE = 20;
    public const int SEARCHES_PER_HOUR = 300;
    public const int BACKOFF_PAUSE_SECONDS = 60;
    public const int WATCH_RETRY_MS = 1000;
    public const int WATCH_SETTLE_MS = 1500;
    public const int REFRESH_GAP_SECONDS = 10;
}
